version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.0
  node: circleci/node@5.0.3
  nx: nrwl/nx@1.6.1
executors:
  with-chrome:
    resource_class: medium
    docker:
      - image: "cypress/base:16.14.2-slim"
jobs:
  e2e:
    docker:
      - image: cimg/node:16.18.1-browsers
    environment:
      DOPPLER_TOKEN: dp.st.ci.0uZw3cZJ76xwRSHRNbNwsNCik3S3RipngU9IEidpnl1
      MAIN_BRANCH_NAME: staging
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          name: Enable permissions for storing Cypress & build assets
          command: |
            chown -R $USER:$USER /home/circleci/project
            mkdir -p dist/cypress
            mkdir -p dist/apps
            chown -R $USER:$USER /home/circleci/project/dist/apps
            chown -R $USER:$USER /home/circleci/project/dist/cypress
            echo */
      - run:
          name: Install Doppler CLI to current directory
          command: (sudo curl -Ls https://cli.doppler.com/install.sh || sudo wget -qO- https://cli.doppler.com/install.sh) | sudo sh
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - nx/set-shas:
          main-branch-name: 'staging'
      - run:
          name: Run workspace lint
          command: yarn nx-cloud record -- yarn nx workspace-lint
      - run:
          name: Run lint
          command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --parallel=3 --target=lint
      - run:
          name: Run backend
          command: sudo doppler run --token=$DOPPLER_TOKEN -- yarn nx serve trok-backend --no-dte
          background: true
      - run:
          name: Run e2e
          environment:
            DOPPLER_TOKEN: dp.st.ci.0uZw3cZJ76xwRSHRNbNwsNCik3S3RipngU9IEidpnl1
          command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=e2e --ci --code-coverage --verbose
      - run:
          name: Run build
          command: sudo yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3 --exclude=trok-backend
      - run:
          name: "Echo current working directory"
          command: |
            root=$(pwd)
            APP_DIR="$root/apps/trok-dashboard-e2e/src/e2e"
            DIST_DIR="$root/dist/cypress/apps/trok-dashboard-e2e"
            echo $(pwd)
            if [ -d "$APP_DIR" ]; then
              # Take action if $DIR exists. #
              echo "Installing config files in ${APP_DIR}..."
            fi
            if [ -d "$DIST_DIR" ]; then
              # Take action if $DIST_DIR exists. #
              echo "Installing config files in ${DIST_DIR}..."
            fi
          when: on_fail
      - store_artifacts:
          path: ./dist/cypress/apps/trok-dashboard-e2e/screenshots/0-auth
          destination: screenshots/0-auth
      - store_artifacts:
          path: ./dist/cypress/apps/trok-dashboard-e2e/videos/0-auth
          destination: videos/0-auth
  deploy:
    docker:
      - image: cimg/node:16.18.1-browsers
    steps:
      - checkout
      - run:
          name: Install cURL library
          command: sudo apt install curl
      - run:
          name: "Deploy to Render"
          command: sudo curl ${tfc_app_deploy_hook_url}
workflows:
  version: 2
  nx-cypress-e2e:
    jobs:
      - e2e:
          context:
            - production
          filters:
            branches:
              only:
                - master
                - staging
      - deploy:
          context:
            - staging
          requires:
            - e2e
          filters:
            branches:
              only:
                - staging