version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0
  node: circleci/node@5.0.3
  nx: nrwl/nx@1.6.1
executors:
  with-chrome:
    resource_class: medium
    docker:
      - image: cimg/node:16.18.1-browsers
jobs:
  main:
    docker:
      - image: cimg/node:16.18.1-browsers
    environment:
      MAIN_BRANCH_NAME: master
    steps:
      - checkout
      - run:
          name: Install Doppler CLI to current directory
          command: (sudo curl -Ls https://cli.doppler.com/install.sh || sudo wget -qO- https://cli.doppler.com/install.sh) | sudo sh
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - nx/set-shas:
          main-branch-name: 'master'
      - run:
          name: Run workspace lint
          command: yarn nx-cloud record -- yarn nx workspace-lint
      - run:
          name: Run lint
          command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=1
      - run:
          name: Run backend
          command: sudo doppler run --token=$DOPPLER_TOKEN_BACKEND -- yarn run nx:backend:serve:ci
          background: true
      - run:
          name: Run e2e
          environment:
            API_BASE_URL: http://localhost:3333
          command: sudo yarn nx affected --base=$NX_BASE --head=$NX_HEAD  --target=e2e --parallel=1 --ci --code-coverage
      - run:
          name: Run build
          command: sudo yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=1 --exclude=trok-backend
      - run:
          name: "Echo current working directory"
          command: |
            root=$(pwd)
            APP_DIR="$root/apps/trok-dashboard-e2e/src/e2e"
            DIST_DIR="$root/dist/cypress/apps/trok-dashboard-e2e"
            echo $(pwd)
            if [ -d "$APP_DIR" ]; then
              # Take action if $DIR exists. #
              echo "Installing config files in ${APP_DIR}..."
            fi
            if [ -d "$DIST_DIR" ]; then
              # Take action if $DIST_DIR exists. #
              echo "Installing config files in ${DIST_DIR}..."
            fi
          when: on_fail
      - store_artifacts:
          path: ./dist/cypress/apps/trok-dashboard-e2e/screenshots/0-auth/*
          destination: screenshots/0-auth
      - store_artifacts:
          path: ./dist/cypress/apps/trok-dashboard-e2e/videos/0-auth/*
          destination: videos/0-auth
      - run:
          name: Stop all agents
          command: yarn nx-cloud stop-all-agents
          when: always
  test:
    docker:
      - image: cimg/node:16.18.1-browsers
    steps:
      - checkout
      - run:
          name: "Echo current working directory"
          command: |
            root=$(pwd)
            DIR="$root/apps/trok-dashboard-e2e/src/e2e"
            echo $(pwd)
            if [ -d "$DIR" ]; then
              # Take action if $DIR exists. #
              echo "Installing config files in ${DIR}..."
            fi
workflows:
  version: 2
  ci:
    jobs:
      #      - test:
      #          name: "Test Run"
      #          filters:
      #            branches:
      #              only:
      #                - staging
      #                - main
      - main:
          name: Nx Cloud Main
          filters:
            branches:
              only:
                - staging
                - main
