version: 2.1

orbs:
    cypress: cypress-io/cypress@2.2.0
    node: circleci/node@5.0.3
    nx: nrwl/nx@1.6.1
executors:
  with-chrome:
    resource_class: medium
    docker:
      - image: "cypress/base:16.14.2-slim"
jobs:
    agent:
        docker:
            - image: cimg/node:16.18.1-browsers
        parameters:
            ordinal:
                type: integer
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: yarn install --frozen-lockfile
            - run:
                  name: Start the agent << parameters.ordinal >>
                  command: yarn nx-cloud start-agent
                  no_output_timeout: 60m
    main:
        docker:
            - image: cimg/node:16.18.1-browsers
        environment:
            MAIN_BRANCH_NAME: master
            NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: yarn install --frozen-lockfile
            - nx/set-shas:
                  main-branch-name: 'master'
            - run:
                  name: Initialize the Nx Cloud distributed CI run
                  command: yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
            - run:
                  name: Run workspace lint
                  command: yarn nx-cloud record -- yarn nx workspace-lint
            - run:
                  name: Run lint
                  command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
            - run:
                  name: Run e2e
                  command:
                      yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=e2e --parallel=3 --ci --code-coverage
            - run:
                  name: Run build
                  command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
            - run:
                  name: Stop all agents
                  command: yarn nx-cloud stop-all-agents
                  when: always

workflows:
    version: 2
    build:
      jobs:
        - cypress/install:
            yarn: true
            executor: with-chrome
            build: yarn run nx:dashboard:build:ci
            filters:
              branches:
                only:
                  - master
                  - dev
        - cypress/run:
            name: cypress/dev/auth
            executor: with-chrome
            requires:
              - cypress/install
            filters:
              branches:
                only:
                  - dev
            yarn: true
            config-file: apps/trok-dashboard-e2e/cypress.config.ts
            no-workspace: true
            parallel: true # split all specs across machines
            parallelism: 4 # use 4 CircleCI machines to finish quickly
            group: 'Auth Tests' # name this group "all tests" on the dashboard
            start: 'yarn run nx:dashboard:serve:ci'
            env: 'API_BASE_URL=http://localhost:3333,BASE_URL=http://localhost:4200'
            store_artifacts: true
            post-steps:
              - store_test_results:
                  path: cypress/results
            tags: 'dev'
    ci:
        jobs:
            - agent:
                  name: Nx Cloud Agent << matrix.ordinal >>
                  matrix:
                      parameters:
                          ordinal: [1, 2, 3]
            - main:
                  name: Nx Cloud Main
