version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0
  node: circleci/node@5.0.3
  nx: nrwl/nx@1.6.1
executors:
  with-chrome:
    resource_class: medium
    docker:
      - image: "cypress/base:16.14.2-slim"
jobs:
  agent:
    docker:
      - image: cimg/node:16.18.1-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Start the agent << parameters.ordinal >>
          command: yarn nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: cimg/node:16.18.1-browsers
    environment:
      MAIN_BRANCH_NAME: master
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - nx/set-shas:
          main-branch-name: 'master'
      - run:
          name: Initialize the Nx Cloud distributed CI run
          command: yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      - run:
          name: Run workspace lint
          command: yarn nx-cloud record -- yarn nx workspace-lint
      - run:
          name: Run lint
          command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
      - run:
          name: Run e2e
          command:
            yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=e2e --parallel=3 --ci --code-coverage
      - store_artifacts:
          path: /home/circleci/project/dist/cypress/apps/trok-dashboard-e2e/screenshots/0-auth
          destination: /screenshots/0-auth
      - store_artifacts:
          path: /home/circleci/project/dist/cypress/apps/trok-dashboard-e2e/videos/0-auth
          destination: /videos/0-auth
      - run:
          name: Run build
          command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
      - run:
          name: Stop all agents
          command: yarn nx-cloud stop-all-agents
          when: always

workflows:
  version: 2
  ci:
    jobs:
      - agent:
          name: Nx Cloud Agent << matrix.ordinal >>
          matrix:
            parameters:
              ordinal: [ 1, 2, 3 ]
          filters:
            branches:
              only:
                - staging
                - main
      - main:
          name: Nx Cloud Main
          filters:
            branches:
              only:
                - staging
                - main
