version: 2.1
orbs:
  nx: nrwl/nx@1.6.1
jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      MAIN_BRANCH_NAME: master
    steps:
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas:
          allow-on-hold-workflow: true
          error-on-no-successful-workflow: true
          main-branch-name: master
          workflow-name: nx-pipeline
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
workflows: null